# Numpy
Bibliotéca do python utillizada para realizar operações numéricas

In [2]:
import numpy as np

In [5]:
# Criar um Array utilzando numpy
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
a[0]

1

In [7]:
a[0] = 11

In [8]:
a

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a[:3]

array([11,  2,  3])

In [13]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[1,2]

6

### size = números de elementos no total
### ndim = numero de dimensões
### shape = número de elementos em cada dimensão

In [18]:
# Printa o número de dimensões de um array
a.ndim

2

In [19]:
a.shape

(3, 3)

In [21]:
len(a.shape) == a.ndim

True

In [22]:
a.size

9

In [25]:
# Ver tipo do dado usando numpy
a.dtype ## int - inteiro, 64 - 64 bits

dtype('int64')

# Básico de criar um array

In [28]:
# Criar uma array com 2 elementos 0
np.zeros(2)

array([0., 0.])

In [29]:
# Criar uma array com 2 elementos 1
np.ones(2)

array([1., 1.])

In [34]:
# Usando empty criamos um array que será preenchido aleatóriamente ou com base na memória do computador
np.empty(2)

array([5.5557e-319, 1.5810e-322])

In [36]:
# Podemos criar um array com um range de elementos
np.arange(5)

array([0, 1, 2, 3, 4])

In [37]:
# Podemos criar um array com um range dividido por intervalos
# O primeiro elemento é o valor inicial, o segundo o valor final, o terceiro o tamanho do intervalo
np.arange(2,9,2)

array([2, 4, 6, 8])

In [43]:
# Dificil explicar, mude no valor num e vai entender
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
# Podemos especificar qual tipo de valor será usado
x = np.ones(2,dtype = np.int64)

In [45]:
x

array([1, 1])

# Adicionando, removendo e organizando elementos

In [8]:
a = np.array([2,5,7,4,6,1,9,8])

In [9]:
np.sort(a)

array([1, 2, 4, 5, 6, 7, 8, 9])

Por padrão o .sort() usa introsort, um método hibrido entre Quicksort, Insertion sort, Heapsort.
Veja mais em "https://11dhanushs.medium.com/intro-sort-a-brief-introduction-f06b419674de"

In [10]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [11]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

In [18]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])